### ISSUE TITLE
Update to version 3.3.0 ?

### ISSUE THREAD

**Issue by phillipkent** [Pscx/Pscx#38]
Can the repo be updated to version 3.3.0 as is now available at https://www.powershellgallery.com/packages/Pscx 

Also to put a link from the README here to https://www.powershellgallery.com/packages/Pscx

It was quite confusing to identify the official site for PSCX, and to know what is the latest version.

**Comment by rkeithhill** [comment]
The repo has been updated to 3.3.0 since we released it from this repo.  The release notes in the root dir are out-of-date which is misleading.  I've embedded the release notes directly into the PSD1 file since publishing to the gallery will automatically extract these release notes.

The suggestion to link to the PSGallery is a good one.  I'll also add instructions on how to install from the gallery.

**Comment by rkeithhill** [comment]
Install instructions have been added and the ReleaseNotes.txt in the repo root have been updated for 3.3.1.
